### ISSUE TITLE
frint-props: create `withProvider`

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint-props#12]
## Expected API usage

```js
withProvider(
  providerName,
  mapperFn,
  appName = null,
)
```

* `providerName`: String
* `mapperFn`: Function that receives the provider value, and returns an Object or Observable
* `appName`: defaults to `null` for App in scope, or name of another Child App

## Think about

Multiple providers.

Should there be a plural `withProviders` function too, or reuse the same function?

**Comment by fahad19** [comment]
Beginning to feel less needed over time.

**Comment by dididinight** [comment]
How is it to work for Travix and continue stealing Jean?

**Comment by fahad19** [comment]
wont-do.
