### ISSUE TITLE
frint-props: create `withObservable` - an easy way to use observables in compose()

### ISSUE THREAD

**Issue by viacheslaff** [frintjs/frint-props#20]
It would be beneficial to have possibility to easily use observables as `compose()` arguments and make emitted values available as props. It can be used to fetch data from providers which return observables.

Example: fetching data from API on component mount and having it available as props. Suppose we have an `api` provider in the app which can fetch a url and return a stream with response.

Implementation can look like this with creation of `withObservable` helper function:
```js
export default observe(function (app, props$) {
  return compose(
    withObservable(
      app.get('api').get$('http://example.com/endpoint.json'),
      res => ({ exampleResponse: res })
    )
  );
})(MyComponent);
```
or by allowing observables right in `compose()`:
```js
const exampleResponse$ = app.get('api')
  .get$('http://example.com/endpoint.json')
  .pipe(map(res => ({ exampleResponse: res })));

export default observe(function (app, props$) {
  return compose(
    exampleResponse$
  );
})(MyComponent);
```

**Comment by fahad19** [comment]
I like the first API better 👍
