### ISSUE TITLE
Allow null as first parameter to withStore function

### ISSUE THREAD

**Issue by leandrooriente** [frintjs/frint-props#28]
Today if you want to map only dispatch functions you should pass a function that returns an empty object as the first parameter. It would be great if we could pass `null` to avoid an unnecessary new function.

Eg:

```javascript
const mapStateToProps = () => ({});

const mapDispatchToProps = {
  doSomething,
};

withStore(mapStateToProps, mapDispatchToProps),
```

To:
```javascript
const mapDispatchToProps = {
  doSomething,
};

withStore(null, mapDispatchToProps),
```

**Comment by fahad19** [comment]
is that how `connect` from `react-redux` is doing it too?

**Comment by leandrooriente** [comment]
https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments

**Comment by fahad19** [comment]
I am cool with this. Please send a PR, and I will add you to the repo just like @avg206 so you can go ahead with the release too later on.
